spring.application.name=search-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


resilience4j.circuitbreaker.instances.File-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.File-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.File-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.File-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.File-service.automatic-transition-from-open-to-half-open-enabled=true

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.File-service.record-exceptions=\
  java.io.IOException,\
  java.util.concurrent.TimeoutException,\
  java.net.ConnectException,\
  feign.FeignException




resilience4j.circuitbreaker.instances.folder-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.folder-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.folder-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.folder-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.folder-service.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.folder-service.record-exceptions=\
  java.io.IOException,\
  java.util.concurrent.TimeoutException,\
  feign.FeignException,\
  java.net.ConnectException



logging.level.root=DEBUG
logging.charset.console=UTF-8


resilience4j.circuitbreaker.instances.File-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.folder-service.register-health-indicator=true

