spring.application.name=File-service
server.port=8081



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include[]=*
management.endpoint.health.show-details=always

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:filedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#spring.datasource.username=sa
#spring.datasource.password=root

